title: Axel Olin's Personal Webpage
author: Axel Olin
theme: minima
email: axelll1@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the personal webpage of Axel Olin. It will hopefully contain
  links to my future code depositions on github, other work-related
  links and documents, and perhaps even some personal stuff.

# social links
twitter_username: AxelOlin2 # DO NOT include the @ character, or else the build will fail!
github_username:  axel-olin # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
